# docker-compose.yml
version: '3.8'

services:
  webapp:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./input:/app/input
      - ./output:/app/output
    environment:
      - OLLAMA_URL=http://ollama:11434
      - AUTH_CONFIG_URL=https://raw.githubusercontent.com/Gops-8/auth-config/main/config.json
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    ports:
      - "11433:11434"
      
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
