version: "3.8"

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit-app
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_URL=http://ollama-api:11434
    depends_on:
      - ollama-api
    networks:
      - app-network

  ollama-api:
    image: ollama/ollama-api:latest  # Replace with the official Ollama image if available
    container_name: ollama-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
